spring.data.rest.basePath=/api

# MongoDB configuration
spring.data.mongodb.host=@mongo_host@
spring.data.mongodb.port=@mongo_port@
spring.data.mongodb.database=wipp

# Data storage root folder configuration
storage.root=/data/WIPP-plugins

# Kubernetes PVC name for WIPP Data volume
kube.wippdata.pvc=@shared_pvc@

# Workflow management configuration
workflow.management.system=@workflow.management.system@
workflow.binary=argo
storage.workflows=/data/WIPP-plugins/workflows
workflow.nodeSelector=@workflow_nodeSelector@
workflow.tolerations=@workflow_tolerations@
workflow.pluginHardwareRequirements.enabled=false
workflow.notifications.url=http://wipp-backend.wipp.svc.cluster.local:8080

# SLURM options
slurm.enabled=false
# WIPP Data path on Slurm cluster
slurm.wippdata.path=@slurm.wippdata.path@

# Job storage configuration
storage.temp.jobs=/data/WIPP-plugins/temp/jobs

# Image storage configuration
storage.collections=/data/WIPP-plugins/collections
storage.collections.upload.tmp=/data/WIPP-plugins/temp/collections

# Stitching storage configuration
storage.stitching=/data/WIPP-plugins/stitching

# Image annotations storage configuration
storage.image.annotations=/data/WIPP-plugins/image-annotations

# Image OME TIFF conversion configuration
ome.converter.threads=@ome_converter_threads@

# Image upload - Flow.js configuration
spring.servlet.multipart.maxFileSize=500MB
spring.servlet.multipart.maxRequestSize=500MB

# JACKSON (JacksonProperties)
spring.jackson.mapper.ACCEPT_CASE_INSENSITIVE_ENUMS = true

# Logging configuration
logging.file.path=logs
logging.level.org.springframework.web=INFO
logging.level.loci.formats.in=WARN
server.tomcat.accessLogEnabled=true

# Server configuration
server.forward-headers-strategy=framework

## Keycloak configuration
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.resourceserver.jwt.issuer-uri=@keycloak_auth_url@/realms/WIPP

# Springdoc configuration
springdoc.swagger-ui.oauth.clientId=wipp-public-client
springdoc.swagger-ui.oauth.clientSecret=placeholder
springdoc.oAuthFlow.authorizationUrl=@keycloak_auth_url@/realms/WIPP/protocol/openid-connect/auth
springdoc.oAuthFlow.tokenUrl=@keycloak_auth_url@/realms/WIPP/protocol/openid-connect/token
springdoc.pathsToMatch=/api/**
springdoc.pathsToExclude=/api/profile/**
springdoc.swagger-ui.displayOperationId=true
