pipeline {
    agent {
        node { label 'polus-nci-eks-deploy' }
    }
    parameters {
        string(name: 'DOCKER_VERSION', defaultValue: '', description: 'The build version to deploy (optional)')
        string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'AWS Region to deploy')
        string(name: 'KUBERNETES_CLUSTER_NAME', defaultValue: 'nci-polus-eks-cluster', description: 'Kubernetes cluster to deploy')
    }
    environment {
        WIPP_PVC_NAME = "wipp-pv-claim"
    }
    stages {
        stage('Checkout source code') {
            steps {
                cleanWs()
                checkout scm
            }
        }
        stage('Deploy to AWS Prod') {
            steps {
                configFileProvider([configFile(fileId: 'env-nci', targetLocation: '.env')]) {
                    withAWS(credentials:'nci-polus-deploy') {
                        sh "aws --region ${AWS_REGION} eks update-kubeconfig --name ${KUBERNETES_CLUSTER_NAME}"
                        sh "cp -f deploy/prod/nci/*.yaml deploy/kubernetes"
                        sh "./deploy.sh"
                    }
                }
            }
        }
    }
}
