# PV for WIPP-backend
kind: PersistentVolume
apiVersion: v1
metadata:
  name: wipp-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/WIPP-plugins"
---
# PVC for WIPP-backend
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: WIPP_PVC_NAME_VALUE
spec:
  storageClassName: manual
  volumeName: wipp-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi